version: '3'

services:
    frontend:
        build: ./videoUI
        ports: 
            - "3000:3000"
        volumes:
            - ./videoUI:/var/www/frontend/
        restart: always
        links:
            - webserver
    webserver:
        build : './nginx'
        ports:
            - "80:80"
        volumes:
            - ./nginx/configuration/:/etc/nginx/conf.d/
        restart: always
        links:
            - backend
    backend:
        build: ./VideoApi
        ports: 
            - "5001:5001"
        volumes: 
            - ./VideoApi:/var/www/api
        environment:
            - DOCKER_IP = host.docker.internal
        restart: always
        links:
            - redis
    redis:
        build: ./redis
        expose:
            - "6379"
        restart: always      



