version: '3'
services:
    frontend:
        build: ./videoUI
        ports: 
            - "3000:3000"
        volumes:
            - ${pwd}/videoUI/frontend_volume:var/www
        container_name: frontend_compose_container
        restart: always
        links:
            - backend
    backend:
        build: ./VideoApi
        ports : 
            - "5000:5000"
        volumes: 
            - ${pwd}/VideoApi/videoapi_volume:/var/www
        container_name: videoapi_compose_container
        restart: always



